distributions:
  severity:
    - normal
    - logistic
    - exponential
    - gamma
    - beta
    - lognormal
    - uniform
  frequency:
    - poisson
    - negative binomial


metrics:
  - aic
  - bic